### ISSUE TITLE
Logging error

### ISSUE THREAD

**Issue by ivirshup** [Teichlab/bbknn#15]
It looks like logging has been broken by an update to scanpy.

It's pretty straight forward to fix the timing error, now `logg.info` returns a date time, which you pass to the next `logg.info` you want to have the elapsed time.

I'm not sure how to replace the `end` argument. @flying-sheep, any suggestion?

**Comment by ivirshup** [comment]
Oh, just saw https://github.com/Teichlab/bbknn/pull/14, sorry about the duplicate!

**Comment by ktpolanski** [comment]
Thanks for letting me know this went live in a release, I'll amend BBKNN accordingly early next week.

**Comment by ktpolanski** [comment]
Apparently, the most recent scanpy in pip is still 1.4.3. @ivirshup when is this logging change actually going to go live? I don't want to push out an update to make this compatible with a version of scanpy that's not on pip yet.

**Comment by iandriver** [comment]
@ktpolanski scanpy pip version is now 1.4.4

**Comment by ktpolanski** [comment]
Thanks for the heads up. I'm encountering some trouble with getting the new logging to cooperate (not just BBKNN-side), popped open an issue on the scanpy repo. Depending on  the outcome, I'll either push a nice, fully compatible version with `deep`, or a stand-in with two logging messages to  circumvent the functionality not cooperating.

**Comment by ktpolanski** [comment]
I failed to get a response on my `deep`-related issues [here](https://github.com/theislab/scanpy/issues/746), and I've waited a week. No point delaying this further, so I'm pushing 1.3.5 to pip. It comes with `deep` syntax, which is non-operational on my end, but at least it matches how scanpy's neighbour function behaves. As such, maybe it'll be operational somewhere in mysterious ways.

EDIT: `deep` got fixed in 1.4.4.post1!
